from typing import Tuple, Set, Iterable, List, TYPE_CHECKING, Any, TypeVar, overload, Generic

T = TypeVar('T')
class ICollection(Generic[T]):
    @property
    def Count(self) -> int: ...
    def __getitem__(self, index: int) -> T: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...

IDictionary = Any
IList = ICollection
Object = Any

if TYPE_CHECKING:
    from Autodesk.Revit.DB import Document, ElementId, XYZ, Reference, Element, ElementSlowFilter


class ISelectionFilter:
    def AllowElement(self, elem: Element) -> bool: ...
    def AllowReference(self, reference: Reference, position: XYZ) -> bool: ...


class PickedBox:
    @property
    def Min(self) -> XYZ: ...
    @Min.setter
    def Min(self, __set_formal: XYZ) -> None: ...
    @property
    def Max(self) -> XYZ: ...
    @Max.setter
    def Max(self, __set_formal: XYZ) -> None: ...


class Selection:
    @overload
    def PickObject(self, objectType: ObjectType, selectionFilter: ISelectionFilter, statusPrompt: str) -> Reference: ...
    @overload
    def PickObject(self, objectType: ObjectType, selectionFilter: ISelectionFilter) -> Reference: ...
    @overload
    def PickObject(self, objectType: ObjectType, statusPrompt: str) -> Reference: ...
    @overload
    def PickObject(self, objectType: ObjectType) -> Reference: ...
    @overload
    def PickObjects(self, objectType: ObjectType, selectionFilter: ISelectionFilter, statusPrompt: str, pPreSelected: IList[Reference]) -> IList[Reference]: ...
    @overload
    def PickObjects(self, objectType: ObjectType, selectionFilter: ISelectionFilter, statusPrompt: str) -> IList[Reference]: ...
    @overload
    def PickObjects(self, objectType: ObjectType, selectionFilter: ISelectionFilter) -> IList[Reference]: ...
    @overload
    def PickObjects(self, objectType: ObjectType, statusPrompt: str) -> IList[Reference]: ...
    @overload
    def PickObjects(self, objectType: ObjectType) -> IList[Reference]: ...
    @overload
    def PickPoint(self, snapSettings: ObjectSnapTypes, statusPrompt: str) -> XYZ: ...
    @overload
    def PickPoint(self, statusPrompt: str) -> XYZ: ...
    @overload
    def PickPoint(self, snapSettings: ObjectSnapTypes) -> XYZ: ...
    @overload
    def PickPoint(self) -> XYZ: ...
    @overload
    def PickBox(self, style: PickBoxStyle, statusPrompt: str) -> PickedBox: ...
    @overload
    def PickBox(self, style: PickBoxStyle) -> PickedBox: ...
    @overload
    def PickElementsByRectangle(self, selectionFilter: ISelectionFilter, statusPrompt: str) -> IList[Element]: ...
    @overload
    def PickElementsByRectangle(self, selectionFilter: ISelectionFilter) -> IList[Element]: ...
    @overload
    def PickElementsByRectangle(self, statusPrompt: str) -> IList[Element]: ...
    @overload
    def PickElementsByRectangle(self) -> IList[Element]: ...
    @property
    def IsValidObject(self) -> bool: ...
    def SetElementIds(self, elementIds: ICollection[ElementId]) -> None: ...
    def GetElementIds(self) -> ICollection[ElementId]: ...
    def GetReferences(self) -> IList[Reference]: ...
    def SetReferences(self, references: IList[Reference]) -> None: ...
    def Dispose(self) -> None: ...


class ObjectType:
    Nothing = 0
    Element = 1
    PointOnElement = 2
    Edge = 3
    Face = 4
    LinkedElement = 5
    Subelement = 6


class ObjectSnapTypes:
    #None = 0
    Endpoints = 1
    Midpoints = 2
    Nearest = 4
    WorkPlaneGrid = 8
    Intersections = 16
    Centers = 32
    Perpendicular = 64
    Tangents = 128
    Quadrants = 256
    Points = 512
    Remote = 1024
    CoordinationModelPoints = 2048


class PickBoxStyle:
    Crossing = 0
    Enclosing = 1
    Directional = 2


class SelectableInViewFilter(ElementSlowFilter):
    @overload
    def __init__(self, document: Document, viewId: ElementId, inverted: bool): ...
    @overload
    def __init__(self, document: Document, viewId: ElementId): ...
